name: Release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add NuGet Package Registry
      run: dotnet nuget add source --username csh --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/csh/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore -o BepInEx/plugins
    - name: Create Release ZIP
      run: |
        rm BepInEx/plugins/*.json
        rm BepInEx/plugins/*.pdb
        zip -r "PlantTimers-${{ github.ref_name }}.zip" BepInEx
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: PlantTimers-${{ github.ref_name }}.zip
